services:
  web:
    build:
      context: .  
      dockerfile: Dockerfile
    ports:
      - "5173:80"  
    depends_on:
      - api
    networks:
      - supmap-network

  api:
    build:
      context: ../supmap-api  
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supmap-database  
      SPRING_DATASOURCE_USERNAME: supmap
      SPRING_DATASOURCE_PASSWORD: supmap
    depends_on:
      - db
    networks:
      - supmap-network

  db:
    image: postgres:latest  
    container_name: supmap-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: supmap-database
      POSTGRES_USER: supmap
      POSTGRES_PASSWORD: supmap
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - supmap-network

networks:
  supmap-network:

volumes:
  postgres_data:
