# Docker Compose - Mode Développement Local - Avec les repos GitHub
name: supmap

services:

  web:
    container_name: supmap-web
    build:
      context: .  # Dossier actuel pour le Web
      dockerfile: Dockerfile
    image: supmap-web
    ports:
      - "${WEB_PORT}:80"
    environment:
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
    depends_on:
      - api
    networks:
      - supmap-network

  api:
    container_name: supmap-api
    build:
      context: ../supmap-api  # Dossier parent pour l'API
      dockerfile: Dockerfile
    image: supmap-api
    ports:
      - "${API_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - supmap-network

  db:
    container_name: supmap-database
    image: postgis/postgis:latest
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - supmap-network

networks:
  supmap-network:

volumes:
  postgres_data:
